name: Build and Push Kong API Gateway to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'         
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tags
        id: tags
        run: |
          # Default tag is "latest" for main branch pushes
          IMAGE_TAG="latest"
          PUSH_LATEST="true"
          
          # If this is a tag push (e.g., v1.0.0 or v1.0.1-rc1)
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            IMAGE_TAG="${VERSION_TAG}"
            
            # Only push "latest" if the tag is a stable release (e.g., v1.0.0)
            if [[ "${VERSION_TAG}" == *-* ]]; then
              PUSH_LATEST="false"
            fi
          fi

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "PUSH_LATEST=${PUSH_LATEST}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/rakete-rso/api-gateway:${{ env.IMAGE_TAG }} -f Dockerfile .

      - name: Push Docker image with version tag
        run: |
          docker push ghcr.io/rakete-rso/api-gateway:${{ env.IMAGE_TAG }}

      - name: Push Docker image as latest
        if: env.PUSH_LATEST == 'true'
        run: |
          docker tag ghcr.io/rakete-rso/api-gateway:${{ env.IMAGE_TAG }} ghcr.io/rakete-rso/api-gateway:latest
          docker push ghcr.io/rakete-rso/api-gateway:latest
